### ISSUE TITLE
Add save & share functionality

### ISSUE THREAD

**Issue by kylestetz** [kylestetz/slang#4]
Users should be able to save their patches to a unique URL for storing and sharing.

Slang is a static site served directly by nginx at the moment, so this will involve adding a super-simple express server (which should still serve `index.html` from `/public` as a static file) with:
- a POST `/save` endpoint that accepts a JSON blob containing a `text` field with the slang code
- a GET `/:patch` route that loads the patch from a mongo database (if it is found) and renders it to a template so that the code can be pre-populated in the editor

Stretch goals:
- add an optional title field
- add a "saved patches" UI which stores the title and URL to localStorage so your saves hang around

**Comment by ghost** [comment]
Wow ;D this is cool
